#!/bin/python3

import math
import os
import random
import re
import sys


def arrayManipulation(n, queries):
   
    # Write your code here
    arr = [0] * (n + 1) 
    for a, b, k in queries: 
        arr[a-1] += k 
        arr[b] -= k 
        max_val = 0 
        current = 0 
        for val in arr: 
            current += val 
            if current > max_val: 
                max_val = current 
    return max_val

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    m = int(first_multiple_input[1])

    queries = []

    for _ in range(m):
        queries.append(list(map(int, input().rstrip().split())))

    result = arrayManipulation(n, queries)

    fptr.write(str(result) + '\n')

    fptr.close()
